name: vosk_flutter
description: Flutter plugin for offline speech recognition using the Vosk speech
  recognition toolkit.
version: 0.4.0
homepage: https://alphacephei.com/
repository: https://github.com/alphacep/vosk-flutter

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  archive: ^4.0.5
  args: ^2.7.0
  build_cli_annotations: ^2.1.0
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  http: ^1.3.0
  package_config: ^2.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pubspec_parse: ^1.5.0

dev_dependencies:
  build_cli: ^2.2.5
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  ffigen: ^18.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

ffigen:
  name: VoskLibrary
  output: "lib/src/generated_vosk_bindings.dart"
  headers:
    entry-points:
      - "vosk-api/src/vosk_api.h"

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter
        pluginClass: VoskFlutterPlugin
      ios:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
      linux:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
      windows:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
